project:
  type: book

book:
  title: "Análisis de Discusiones sobre Inteligencia Artificial en Reddit"
  subtitle: "Trabajo de Fin de Grado"
  author: "Marta Muñoz Aguilar"
  date: today # Usa la fecha actual al compilar
  chapters:
    - index.qmd
    - preprocesamiento.qmd
    - sna.qmd
    - sentimientos.qmd
    - topic.qmd
    - fca.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
lang: es # Configura el idioma a español (Índice, Capítulos, etc.)

crossref:
  fig-title: Figura
  tbl-title: Tabla

execute:
  freeze: auto
  warning: false
  message: false
  echo: true # Muestra el código por defecto, útil para TFG de ingeniería

format:
  html:
    theme: cosmo
    code-fold: true       # Permite ocultar/mostrar el código para facilitar la lectura
    code-tools: true      # Añade un botón para copiar el código
    toc-depth: 3
    number-sections: true
  pdf:
    documentclass: scrreprt
    papersize: a4
    mainfont: "Times New Roman"
    fontsize: 12pt
    linestretch: 1.5
    geometry:
      - top=2.5cm
      - bottom=2.5cm
      - left=3cm
      - right=2.5cm
    toc: true
    toc-depth: 3
    number-sections: true
    colorlinks: true
    keep-tex: false